# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]   # 每小时更新
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 必须要写权限
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # 你的 GitHub Token（可以继续用 METRICS_TOKEN）
          token: ${{ secrets.METRICS_TOKEN }}

          # ⚠️ 用内置 GITHUB_TOKEN 提交 README.md，避免 push 卡住
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: master   # 改成 main 如果你的默认分支是 main
          committer_message: "chore(metrics): update metrics [skip ci]"

          # Options
          user: icecliffs
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Hong_Kong

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_people: yes
          plugin_people_limit: 10
          plugin_people_size: 40
          plugin_people_types: followers, following

          plugin_projects: yes
          plugin_projects_limit: 4
