name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 之前的 GitHub Metrics 步骤
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: icecliffs
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/Hong_Kong
          plugin_achievements: yes
          plugin_achievements_display: summary
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_people: yes
          plugin_people_limit: 10
          plugin_people_size: 40
          plugin_people_types: followers, following

      - name: Anilist
        uses: lowlighter/metrics@latest
        with:
          filename: anilist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_order: anilist
          config_timezone: Asia/Shanghai
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites,watching,characters
          plugin_anilist_limit: 1
          plugin_anilist_limit_characters: 22
          plugin_anilist_shuffle: no
          plugin_anilist_user: icecliffs
